### PR TITLE
Refactor/improve ts inference

### PR DESCRIPTION
**Pull request by liuruenshen**
## Implementation
The Pull Request makes both `getFieldsValue` and `getFieldsValue` functions are capable of inferring the accurate TypeScript type of return values from the given arguments. 

Also, when the developer enters the argument's values, a list of available property names extracted from the type parameter passed through the `useForm` function can be shown to improve the developer experience.

## Demo
Screenshot from 2021-09-19 16-56-56
Screenshot from 2021-09-19 17-00-29
Screenshot from 2021-09-19 17-01-26
Screenshot from 2021-09-19 17-01-45
Screenshot from 2021-09-19 17-02-09
Screenshot from 2021-09-19 17-02-36
Screenshot from 2021-09-19 17-02-59
Screenshot from 2021-09-19 17-03-10
Screenshot from 2021-09-19 17-03-42
Screenshot from 2021-09-19 17-03-55
Screenshot from 2021-09-19 17-04-09
Screenshot from 2021-09-19 17-06-34
Screenshot from 2021-09-19 17-06-56
Screenshot from 2021-09-19 17-07-42

### CODE REVIEW

**Comment by liuruenshen** [comment]
Does anyone here review for this PR?

**Comment by blockchainGuru1018** [comment]
Can you rebase this PR from master branch? @liuruenshen

**Review by blockchainGuru1018 — APPROVED** [review]

**Comment by liuruenshen** [comment]
> Does anyone here review for this PR?

Sure, I will make sure it works well after rebasing.

**Review by blockchainGuru1018 — APPROVED** [review]

**Comment by liuruenshen** [comment]
> > Does anyone here review for this PR?
> 
> Sure, I will make sure it works well after rebasing.

I tested it and it works as expected. You can merge the PR. Thank you.

**Pull request closed without merging**
