### PR TITLE
feat: validate add label

### PR DESCRIPTION
**Pull request by qq645381995**
类似于这样，添加 `label` 。

### CODE REVIEW

**Comment by zombieJ** [comment]
有点管多了，如果是需要定制消息的话应该使用 `rule` 里的 `message`。Field 本身应该是解耦的。

**Comment by qq645381995** [comment]
唉，我们这边场景是：请输入${label}  ，哈哈哈。

**Comment by ghmendonca** [comment]
Why this is closed? This is exactly what I need and exactly what rc-form has. Usually you want the name of the field to be something but in the validate message you want to display something different.. For instance, my field name is full_name and it's required, I don't want to show the message: 'full_name' is required to the user, instead I want to show Full name is required, something like that.. Also, the idea to add the custom message to the field to match the message that I want is very dumb because I would have to add the custom message for every input in my entire application.

Please @zombieJ , consider merging this PR or provide me someway to achieve this.

Thanks

**Comment by zombieJ** [comment]
@ghmendonca https://github.com/react-component/field-form/pull/80

**Comment by crazyair** [comment]
> @ghmendonca #80

算了，不是我想要的，`label` 和  `messageVariables ` 还要写两次名称，我最后用了自动添加一条 rules 
https://github.com/crazyair/father-doc-yform/blob/master/packages/yform/src/YForm/Items.tsx#L152

**Comment by ghmendonca** [comment]
@zombieJ I can work with #80 , I just need the PR to be merged

**Pull request closed without merging**
